# Generated by Django 5.2.6 on 2026-10-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_soft_delete_aware_unique_and_unicode_slugs'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='storeitem',
            name='uniq_store_variant',
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=170, unique=True),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='sku',
            field=models.CharField(help_text='A unique identifier for this product in the store', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uniq_live_store_name'),
        ),
        migrations.AddConstraint(
            model_name='storeitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('store', 'variant'), name='uniq_store_variant'),
        ),
        migrations.AddConstraint(
            model_name='storeitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('sku',), name='uniq_live_storeitem_sku'),
        ),
    ]
