# Generated by Django 5.2.6 on 2026-10-04 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_images'),
        ('marketplace', '0003_store_profile_and_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='storeitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__lte', 100)), name='storeitem_discount_0_100'),
        ),
    ]
