# Generated by Django 5.2.6 on 2026-10-04 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('marketplace', '0001_initial'),
        ('reviews', '0002_add_soft_delete_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='storereview',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'product'), name='uniq_live_product_review_per_user'),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='product_review_rating_1_5'),
        ),
        migrations.AddConstraint(
            model_name='storereview',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'store'), name='uniq_live_store_review_per_user'),
        ),
        migrations.AddConstraint(
            model_name='storereview',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='store_review_rating_1_5'),
        ),
    ]
