"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(h9uh*#&f3&ddejqu=p$2)0@9t(j-d3#ns84dg$ez%#@bamfn^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'accounts',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

permission_classes = [
    'rest_framework.permissions.IsAuthenticated',
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Maktab 130 â€“ Custom Shop Backend",
    "DESCRIPTION": (
        "Ø³Ø±ÙˆÛŒØ³ Ø¨Ú©â€ŒØ§Ù†Ø¯ ÙØ±ÙˆØ´Ú¯Ø§Ù‡ÛŒ Ú†Ù†Ø¯ÙØ±ÙˆØ´Ù†Ø¯Ù‡.\n"
        "Ø´Ø§Ù…Ù„ Ø§Ø­Ø±Ø§Ø² Ù‡ÙˆÛŒØª (JWT/OTP)ØŒ Ù¾Ø±ÙˆÙØ§ÛŒÙ„/Ø¢Ø¯Ø±Ø³ØŒ ÙØ±ÙˆØ´Ù†Ø¯Ù‡/ÙØ±ÙˆØ´Ú¯Ø§Ù‡ØŒ "
        "Ø¯Ø³ØªÙ‡â€ŒØ¨Ù†Ø¯ÛŒ/Ù…Ø­ØµÙˆÙ„ØŒ Ø³Ø¨Ø¯ Ø®Ø±ÛŒØ¯/Ø³ÙØ§Ø±Ø´ØŒ Ù¾Ø±Ø¯Ø§Ø®ØªØŒ Ùˆ Ù¾Ù†Ù„ Ø§Ø¯Ù…ÛŒÙ†."
    ),
    "VERSION": "1.0.0",

    "SERVERS": [
        {"url": "http://127.0.0.1:8000", "description": "Local"},
    ],

    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api",
    "SECURITY": [{"BearerAuth": []}],
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },

    "SORT_OPERATIONS": True,
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,   # ØªÙˆÚ©Ù† Ø¨Ø¹Ø¯ Ø±ÙØ±Ø´ ØµÙØ­Ù‡ Ù‡Ù… Ù…ÛŒâ€ŒÙ…Ø§Ù†Ø¯
        "displayRequestDuration": True,
    },

    "TAGS": [
        {"name": "Auth", "description": "Ø«Ø¨Øªâ€ŒÙ†Ø§Ù…ØŒ ÙˆØ±ÙˆØ¯ØŒ Ø±ÙØ±Ø´ØŒ OTP"},
        {"name": "Profile", "description": "Ù¾Ø±ÙˆÙØ§ÛŒÙ„ Ùˆ Ø¢Ø¯Ø±Ø³â€ŒÙ‡Ø§ÛŒ Ú©Ø§Ø±Ø¨Ø±"},
        {"name": "Store", "description": "Ø«Ø¨Øªâ€ŒÙ†Ø§Ù… ÙØ±ÙˆØ´Ù†Ø¯Ù‡ Ùˆ Ù…Ø¯ÛŒØ±ÛŒØª ÙØ±ÙˆØ´Ú¯Ø§Ù‡"},
        {"name": "Catalog", "description": "Ø¯Ø³ØªÙ‡â€ŒØ¨Ù†Ø¯ÛŒâ€ŒÙ‡Ø§ Ùˆ Ù…Ø­ØµÙˆÙ„Ø§Øª"},
        {"name": "Cart & Orders", "description": "Ø³Ø¨Ø¯ Ø®Ø±ÛŒØ¯ Ùˆ Ø³ÙØ§Ø±Ø´"},
        {"name": "Payments", "description": "Ù¾Ø±Ø¯Ø§Ø®Øª Ùˆ ØªØ£ÛŒÛŒØ¯"},
        {"name": "Admin", "description": "Ø¹Ù…Ù„ÛŒØ§Øª Ù…Ø¯ÛŒØ±ÛŒØªÛŒ"},
    ],
}


CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
