# Generated by Django 5.2.6 on 2026-10-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_soft_delete_aware_unique_and_unicode_slugs'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='uniq_cart_storeitem',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('cart', 'store_item'), name='uniq_cart_storeitem'),
        ),
    ]
