# Generated by Django 5.2.6 on 2026-10-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_soft_delete_aware_cart_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
